"""Phase 4 production regression tests for validation artifact files.

Verify that the Phase 4 artifact JSON files exist in the
artifacts/validation/ directory and have the expected top-level structure.

The artifacts are generated by ``scripts/generate_phase4_artifacts.py`` and
use ``schema_version`` ``1.0``.  The expected keys mirror the generator
output, not the legacy hand-written format.

Also tests the Fail Fast validation logic of the generator script.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

_ARTIFACTS_DIR = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "artifacts",
    "validation",
)

_SCRIPT_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "scripts",
    "generate_phase4_artifacts.py",
)

_EXPECTED_FILES = (
    "phase4-answerability-matrix.json",
    "phase4-validation-code-matrix.json",
    "phase4-policy-matrix.json",
    "phase4-api-contract.json",
    "phase4-streaming-safety.json",
    "phase4-non-validation-parity.json",
    "phase4-acceptance.json",
)

_ANSWERABILITY_STATUSES = (
    "answerable",
    "not_answerable",
    "partially_answerable",
    "calculation_blocked",
)

_INTENT_NAMES = (
    "financial_calculation",
    "document_qa",
    "front_matter",
    "conversation",
)


def _get_git_commit() -> str:
    """Return current git HEAD SHA."""
    import subprocess

    root = os.path.join(os.path.dirname(__file__), "..", "..")
    try:
        return (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd=root,
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
    except Exception:
        return ""


def _load_artifact(name: str) -> dict:
    """Load an artifact JSON file as a dict."""
    path = os.path.join(_ARTIFACTS_DIR, name)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# 1-7: Structure tests
# ---------------------------------------------------------------------------


def test_artifacts_directory_exists() -> None:
    """1. The artifacts/validation/ directory must exist."""
    assert os.path.isdir(_ARTIFACTS_DIR), (
        f"artifacts directory not found: {_ARTIFACTS_DIR}"
    )


def test_all_seven_artifact_files_exist() -> None:
    """2. All seven Phase 4 artifact JSON files must exist."""
    assert os.path.isdir(_ARTIFACTS_DIR), (
        f"artifacts directory not found: {_ARTIFACTS_DIR}"
    )
    missing = [
        name
        for name in _EXPECTED_FILES
        if not os.path.isfile(os.path.join(_ARTIFACTS_DIR, name))
    ]
    assert not missing, f"missing artifact files: {missing}"


def test_answerability_matrix_structure() -> None:
    """3. answerability-matrix.json must have a 'statuses' list."""
    data = _load_artifact("phase4-answerability-matrix.json")
    assert "statuses" in data
    assert isinstance(data["statuses"], list)
    assert len(data["statuses"]) > 0
    serialized = json.dumps(data)
    assert any(status in serialized for status in _ANSWERABILITY_STATUSES), (
        "no canonical answerability status found in answerability matrix"
    )


def test_validation_code_matrix_structure() -> None:
    """4. validation-code-matrix.json must have a 'codes' key."""
    data = _load_artifact("phase4-validation-code-matrix.json")
    assert "codes" in data


def test_policy_matrix_structure() -> None:
    """5. policy-matrix.json must have an 'intents' dict keyed by intent name."""
    data = _load_artifact("phase4-policy-matrix.json")
    assert "intents" in data
    assert isinstance(data["intents"], dict)
    serialized = json.dumps(data)
    assert any(intent in serialized for intent in _INTENT_NAMES), (
        "no canonical intent name found in policy matrix"
    )


def test_streaming_safety_structure() -> None:
    """6. streaming-safety.json must have a 'checks' list."""
    data = _load_artifact("phase4-streaming-safety.json")
    assert "checks" in data
    assert isinstance(data["checks"], list)
    assert len(data["checks"]) > 0


def test_acceptance_structure() -> None:
    """7. acceptance.json must have a 'criteria' list with 55 items."""
    data = _load_artifact("phase4-acceptance.json")
    assert "criteria" in data
    assert isinstance(data["criteria"], list)
    assert len(data["criteria"]) == 55, (
        f"expected 55 criteria, found {len(data['criteria'])}"
    )
    total = len(data["criteria"])
    passed = sum(1 for c in data["criteria"] if c.get("status") == "pass")
    assert 0 <= passed <= total


# ---------------------------------------------------------------------------
# 8-14: Fail Fast validation tests
# ---------------------------------------------------------------------------


def test_acceptance_not_all_true_blindly() -> None:
    """8. Each criterion must carry a non-empty 'criterion' text."""
    data = _load_artifact("phase4-acceptance.json")
    criteria = data["criteria"]
    assert isinstance(criteria, list)
    assert len(criteria) > 0
    for criterion in criteria:
        assert "criterion" in criterion, (
            f"criterion missing 'criterion' text: {criterion}"
        )
        text = criterion.get("criterion")
        assert isinstance(text, str) and text.strip(), (
            f"criterion has empty criterion text: {criterion}"
        )


def test_generated_commit_matches_implementation() -> None:
    """9. generated_commit must equal the implementation commit from manifest."""
    data = _load_artifact("phase4-acceptance.json")
    manifest = _load_artifact("phase4-test-results.json")
    impl_commit = manifest["implementation_commit"]
    assert impl_commit, "manifest has no implementation_commit"
    assert data["generated_commit"] == impl_commit, (
        "generated_commit {} != implementation_commit {}".format(
            data["generated_commit"], impl_commit
        )
    )


def test_script_succeeds_with_exit_code_zero() -> None:
    """10. The artifact generation script must exit with code 0."""
    result = subprocess.run(
        [sys.executable, _SCRIPT_PATH],
        capture_output=True,
        text=True,
        cwd=os.path.join(os.path.dirname(__file__), "..", ".."),
    )
    assert result.returncode == 0, (
        f"script exited with {result.returncode}:\n{result.stderr}"
    )


def test_all_acceptance_ids_unique() -> None:
    """11. All acceptance criterion IDs must be unique."""
    data = _load_artifact("phase4-acceptance.json")
    ids = [c["id"] for c in data["criteria"]]
    assert len(ids) == len(set(ids)), "duplicate acceptance IDs found"


def test_all_acceptance_have_evidence() -> None:
    """12. Every acceptance criterion must have at least one evidence item."""
    data = _load_artifact("phase4-acceptance.json")
    for criterion in data["criteria"]:
        evidence = criterion.get("evidence", [])
        assert len(evidence) > 0, f"criterion {criterion['id']} has no evidence"


def test_all_acceptance_status_is_pass() -> None:
    """13. All 55 acceptance criteria must have status 'pass'."""
    data = _load_artifact("phase4-acceptance.json")
    for criterion in data["criteria"]:
        assert criterion["status"] == "pass", (
            f"criterion {criterion['id']} has status "
            f"'{criterion['status']}' (expected 'pass')"
        )


def test_test_results_manifest_has_no_failures() -> None:
    """14. The test results manifest must show 0 failures and 0 errors."""
    manifest_path = os.path.join(_ARTIFACTS_DIR, "phase4-test-results.json")
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    for cmd in manifest["commands"]:
        if "failed" in cmd:
            assert cmd["failed"] == 0, (
                f"command '{cmd['command']}' has {cmd['failed']} failures"
            )
            assert cmd.get("errors", 0) == 0, (
                f"command '{cmd['command']}' has {cmd.get('errors', 0)} errors"
            )
        else:
            assert cmd["status"] == "pass", (
                f"command '{cmd['command']}' has status '{cmd['status']}'"
            )
