"""Phase 4 production regression tests for validation artifact files.

Verify that the Phase 4 artifact JSON files exist in the
artifacts/validation/ directory and have the expected top-level structure.

The artifacts are generated by ``scripts/generate_phase4_artifacts.py`` and
use ``schema_version`` ``1.0``.  The expected keys mirror the generator
output, not the legacy hand-written format.
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

_ARTIFACTS_DIR = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "artifacts",
    "validation",
)

_EXPECTED_FILES = (
    "phase4-answerability-matrix.json",
    "phase4-validation-code-matrix.json",
    "phase4-policy-matrix.json",
    "phase4-api-contract.json",
    "phase4-streaming-safety.json",
    "phase4-non-validation-parity.json",
    "phase4-acceptance.json",
)

#: Canonical answerability status values (lowercase, matching
#: ``AnswerabilityStatus`` enum ``.value``).
_ANSWERABILITY_STATUSES = (
    "answerable",
    "not_answerable",
    "partially_answerable",
    "calculation_blocked",
)

#: Canonical intent names present in the policy matrix.
_INTENT_NAMES = (
    "financial_calculation",
    "document_qa",
    "front_matter",
    "conversation",
)


def _load_artifact(name: str) -> dict:
    """Load an artifact JSON file as a dict."""
    path = os.path.join(_ARTIFACTS_DIR, name)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def test_artifacts_directory_exists() -> None:
    """The artifacts/validation/ directory must exist."""
    assert os.path.isdir(_ARTIFACTS_DIR), (
        f"artifacts directory not found: {_ARTIFACTS_DIR}"
    )


def test_all_seven_artifact_files_exist() -> None:
    """All seven Phase 4 artifact JSON files must exist."""
    assert os.path.isdir(_ARTIFACTS_DIR), (
        f"artifacts directory not found: {_ARTIFACTS_DIR}"
    )
    missing = [
        name
        for name in _EXPECTED_FILES
        if not os.path.isfile(os.path.join(_ARTIFACTS_DIR, name))
    ]
    assert not missing, f"missing artifact files: {missing}"


def test_answerability_matrix_structure() -> None:
    """answerability-matrix.json must have a 'statuses' list with answerability statuses."""
    data = _load_artifact("phase4-answerability-matrix.json")
    assert "statuses" in data
    assert isinstance(data["statuses"], list)
    assert len(data["statuses"]) > 0
    serialized = json.dumps(data)
    assert any(status in serialized for status in _ANSWERABILITY_STATUSES), (
        "no canonical answerability status found in answerability matrix"
    )


def test_validation_code_matrix_structure() -> None:
    """validation-code-matrix.json must have a 'codes' key with validation error codes."""
    data = _load_artifact("phase4-validation-code-matrix.json")
    assert "codes" in data


def test_policy_matrix_structure() -> None:
    """policy-matrix.json must have an 'intents' dict keyed by intent name."""
    data = _load_artifact("phase4-policy-matrix.json")
    assert "intents" in data
    assert isinstance(data["intents"], dict)
    serialized = json.dumps(data)
    assert any(intent in serialized for intent in _INTENT_NAMES), (
        "no canonical intent name found in policy matrix"
    )


def test_api_contract_structure() -> None:
    """api-contract.json must have an 'endpoints' key."""
    data = _load_artifact("phase4-api-contract.json")
    assert "endpoints" in data


def test_streaming_safety_structure() -> None:
    """streaming-safety.json must have a 'checks' list of safety checks."""
    data = _load_artifact("phase4-streaming-safety.json")
    assert "checks" in data
    assert isinstance(data["checks"], list)
    assert len(data["checks"]) > 0


def test_acceptance_structure() -> None:
    """acceptance.json must have a 'criteria' list (55 items) with per-item status.

    The generator does not emit top-level 'total'/'passed' counters; those
    are derived from the criteria list to avoid drift.
    """
    data = _load_artifact("phase4-acceptance.json")
    assert "criteria" in data
    assert isinstance(data["criteria"], list)
    assert len(data["criteria"]) > 0
    # Derived counts (replaces legacy top-level total/passed keys).
    total = len(data["criteria"])
    passed = sum(1 for c in data["criteria"] if c.get("status") == "pass")
    assert 0 <= passed <= total


def test_acceptance_not_all_true_blindly() -> None:
    """acceptance.json must not blindly set everything to pass without a criterion text.

    Each criterion must carry a non-empty 'criterion' description so that a
    passing acceptance record is auditable rather than a rubber stamp.
    """
    data = _load_artifact("phase4-acceptance.json")
    criteria = data["criteria"]
    assert isinstance(criteria, list)
    assert len(criteria) > 0
    for criterion in criteria:
        assert "criterion" in criterion, (
            f"criterion missing 'criterion' text: {criterion}"
        )
        text = criterion.get("criterion")
        assert isinstance(text, str) and text.strip(), (
            f"criterion has empty criterion text: {criterion}"
        )
