"""Phase 4 baseline characterization tests.

This file fixes the EXACT behavior of the Phase 3 production system BEFORE
any Phase 4 grounding/validation logic is introduced. It makes no changes to
production code. Every assertion here documents a pre-validation invariant
that Phase 4 must preserve (or deliberately and explicitly change in a later
commit).

The 12 characterized behaviors (per Phase 4 spec section 5):
 1. Calculation EXECUTED returns the rendered deterministic answer directly.
 2. Calculation BLOCKED returns a deterministic refusal (no LLM).
 3. Calculation FAILED returns a safe failure message (no stack, no LLM).
 4. Ordinary document QA is generated by the LLM.
 5. Ordinary numeric lookup can be handled by the deterministic extractor.
 6. Insufficient-evidence ordinary questions may still enter the LLM.
 7. ``context_sufficient`` reflects the sufficiency evaluator output.
 8. ``sources`` is the list produced by ``ContextBuilder.build``.
 9. HTTP ``/query`` returns the current field set (no validation field).
10. SSE ``done`` event carries the current field set (no validation field).
11. Trace ``diagnostics`` carries the current field set (no validation key).
12. Non-calculation answers currently have NO ``validation`` field.

If any of these assertions change during Phase 4, the change MUST be made in
a later commit (not this one) and this file updated accordingly so the
behavioral delta is explicit and reviewable.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
from unittest.mock import AsyncMock, MagicMock, patch

# Mock heavy/unavailable imports before importing app modules (mirrors
# tests/refactor/conftest.py pattern).
for _mod in [
    "chromadb", "chromadb.utils", "chromadb.utils.embedding_functions",
    "camelot", "pymupdf", "langchain", "langchain_core",
    "langchain_core.documents", "langchain_text_splitters", "jieba_fast",
]:
    if _mod not in sys.modules:
        sys.modules[_mod] = MagicMock()
sys.modules["jieba_fast"].cut_for_search = lambda text: [text]

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

from src.application.rag_orchestrator import RAGOrchestrator  # noqa: E402
from src.domain.calculation import (  # noqa: E402
    CalculationOperand,
    CalculationOperation,
    CalculationResult,
    CalculationStatus,
)
from src.domain.query import QueryRequest  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run(coro):
    return asyncio.new_event_loop().run_until_complete(coro)


def _chunk(content="Revenue was 1250 million in FY2024.", chunk_id="chunk_001",
           document_name="annual_report.pdf", page=12, score=0.95):
    return {
        "chunk_id": chunk_id,
        "doc_id": chunk_id,
        "content": content,
        "document_name": document_name,
        "page": page,
        "metadata": {"document_name": document_name, "page": page},
        "score": score,
    }


def _make_orchestrator(*, calculation_pipeline=None):
    """Build a RAGOrchestrator with all boundaries mocked.

    The orchestrator itself is real; only its injected dependencies
    (retrieval, LLM, context builder, trace, intent) are mocked so we can
    drive each branch deterministically.
    """
    orch = RAGOrchestrator(
        query_processor=MagicMock(),
        retrieval_pipeline=MagicMock(),
        context_builder=MagicMock(),
        sufficiency_evaluator=MagicMock(),
        llm_gateway=MagicMock(),
        deterministic_extractor=MagicMock(),
        trace_logger=MagicMock(),
        intent_classifier=MagicMock(),
        list_all_documents_fn=MagicMock(return_value=[{"name": "annual_report.pdf"}]),
        get_front_matter_chunks_fn=MagicMock(return_value=[]),
        calculation_pipeline=calculation_pipeline,
    )
    # Defaults that route through the full RAG path.
    orch._classify_intent = MagicMock(return_value={
        "intent": "document_qa", "confidence": 0.8, "requires_retrieval": True,
        "reason": "test",
    })
    orch._handle_conversational_query = MagicMock(return_value=None)
    orch._query_processor.is_title_query = MagicMock(return_value=False)
    orch._query_processor.should_generate_with_low_confidence = MagicMock(return_value=False)
    orch._retrieve_front_matter_chunks = MagicMock(return_value=[])
    orch._retrieval_pipeline.retrieve_single = MagicMock(return_value=[_chunk()])
    orch._retrieval_pipeline.retrieve_multiple = AsyncMock(return_value=[_chunk()])
    orch._retrieval_pipeline._last_retrieval_debug = {}
    orch._context_builder.build = MagicMock(return_value=("context text", [
        {"doc_id": "chunk_001", "page": 12, "filename": "annual_report.pdf",
         "type": "text", "score": 0.95},
    ]))
    orch._sufficiency_evaluator.evaluate = MagicMock(
        return_value=MagicMock(is_sufficient=True)
    )
    orch._sufficiency_evaluator.confidence = MagicMock(return_value=0.9)
    orch._deterministic_extractor.answer_front_matter_query = MagicMock(return_value=None)
    orch._deterministic_extractor.answer_deterministic_query_from_context = MagicMock(
        return_value=None
    )
    orch._llm_gateway.generate = AsyncMock(return_value="LLM generated answer.")
    orch._llm_gateway.rewrite_query = AsyncMock(return_value="rewritten")
    orch._trace_logger.log = MagicMock(return_value="trace_phase4_baseline_001")
    return orch


def _executed_result():
    return CalculationResult(
        status=CalculationStatus.EXECUTED,
        operation=CalculationOperation.GROSS_MARGIN,
        value=__import__("decimal").Decimal("0.4000"),
        unit="ratio",
        formula="gross_margin = gross_profit / revenue",
        formula_version="gross_margin.v1",
        target_metric="gross_margin",
        operands=(
            CalculationOperand(
                name="gross_profit", value=__import__("decimal").Decimal("500"),
                unit="base", scale="million",
                source_text="Gross profit was 500 million.",
                evidence_chunk_id="chunk_001",
                document_name="annual_report.pdf", page=12,
            ),
            CalculationOperand(
                name="revenue", value=__import__("decimal").Decimal("1250"),
                unit="base", scale="million",
                source_text="Revenue was 1250 million.",
                evidence_chunk_id="chunk_001",
                document_name="annual_report.pdf", page=12,
            ),
        ),
    )


class _StubPipeline:
    """Minimal stub honoring the CalculationPipeline.try_calculate contract."""

    def __init__(self, result):
        self._result = result

    def try_calculate(self, question, intent, evidence):
        return self._result


# ---------------------------------------------------------------------------
# 1-3: Calculation branches (EXECUTED / BLOCKED / FAILED)
# ---------------------------------------------------------------------------

class TestCalculationBranchBaseline:
    def test_executed_returns_rendered_answer_directly(self):
        orch = _make_orchestrator(
            calculation_pipeline=_StubPipeline(_executed_result())
        )
        result = _run(orch.answer(QueryRequest(question="gross margin?", user_id=1)))
        # The answer must be the deterministic rendered string (not the LLM).
        assert "Gross Margin" in result.answer or "gross margin" in result.answer.lower()
        assert "40.00%" in result.answer
        orch._llm_gateway.generate.assert_not_called()
        # calculations tuple carries the public dict.
        assert len(result.calculations) == 1
        assert result.calculations[0]["status"] == "executed"
        # Public dict must NOT expose error_message or source_text.
        assert "error_message" not in result.calculations[0]

    def test_blocked_returns_deterministic_refusal(self):
        blocked = CalculationResult(
            status=CalculationStatus.BLOCKED,
            operation=CalculationOperation.GROSS_MARGIN,
            target_metric="gross_margin",
            error_code="OPERAND_MISSING",
            error_message="could not find revenue operand",
        )
        orch = _make_orchestrator(calculation_pipeline=_StubPipeline(blocked))
        result = _run(orch.answer(QueryRequest(question="gross margin?", user_id=1)))
        assert "Unable to compute" in result.answer
        orch._llm_gateway.generate.assert_not_called()
        assert result.calculations[0]["status"] == "blocked"

    def test_failed_returns_safe_failure_without_stack(self):
        failed = CalculationResult(
            status=CalculationStatus.FAILED,
            operation=CalculationOperation.GROSS_MARGIN,
            target_metric="gross_margin",
            error_code="INTERNAL_ERROR",
            error_message="ZeroDivisionError: division by zero at line 42",
        )
        orch = _make_orchestrator(calculation_pipeline=_StubPipeline(failed))
        result = _run(orch.answer(QueryRequest(question="gross margin?", user_id=1)))
        # Safe message, no stack leak.
        assert "internal calculation error" in result.answer.lower()
        assert "ZeroDivisionError" not in result.answer
        assert "line 42" not in result.answer
        orch._llm_gateway.generate.assert_not_called()
        # Public payload excludes error_message.
        assert "error_message" not in result.calculations[0]


# ---------------------------------------------------------------------------
# 4-6: Document QA / deterministic / insufficient paths
# ---------------------------------------------------------------------------

class TestDocumentQABaseline:
    def test_ordinary_document_qa_uses_llm(self):
        orch = _make_orchestrator()
        result = _run(orch.answer(QueryRequest(question="summarize the report", user_id=1)))
        assert result.answer == "LLM generated answer."
        orch._llm_gateway.generate.assert_awaited_once()

    def test_deterministic_extractor_can_short_circuit_llm(self):
        orch = _make_orchestrator()
        orch._deterministic_extractor.answer_deterministic_query_from_context.return_value = {
            "answer": "Deterministic numeric answer.",
            "diagnostic": {"path": "deterministic_context"},
        }
        result = _run(orch.answer(QueryRequest(question="what was revenue", user_id=1)))
        assert result.answer == "Deterministic numeric answer."
        orch._llm_gateway.generate.assert_not_called()

    def test_insufficient_evidence_may_still_call_llm(self):
        """Phase 3 behavior: low-confidence numeric override can force LLM even
        when sufficiency is False. This documents that Phase 3 does NOT have a
        hard pre-generation answerability gate."""
        orch = _make_orchestrator()
        orch._sufficiency_evaluator.evaluate.return_value = MagicMock(is_sufficient=False)
        orch._query_processor.should_generate_with_low_confidence.return_value = True
        result = _run(orch.answer(QueryRequest(question="revenue growth", user_id=1)))
        # Phase 3 allows LLM generation despite insufficient context.
        orch._llm_gateway.generate.assert_awaited_once()
        # The refusal message is NOT used when the override is active.
        assert result.answer == "LLM generated answer."


# ---------------------------------------------------------------------------
# 7-8: Sufficiency and sources structure
# ---------------------------------------------------------------------------

class TestSufficiencyAndSourcesBaseline:
    def test_context_sufficient_reflects_evaluator(self):
        orch = _make_orchestrator()
        orch._sufficiency_evaluator.evaluate.return_value = MagicMock(is_sufficient=False)
        orch._query_processor.should_generate_with_low_confidence.return_value = False
        result = _run(orch.answer(QueryRequest(question="revenue", user_id=1)))
        assert result.context_sufficient is False

    def test_sources_match_context_builder_output(self):
        orch = _make_orchestrator()
        expected_sources = [
            {"doc_id": "chunk_001", "page": 12, "filename": "annual_report.pdf",
             "type": "text", "score": 0.95},
        ]
        orch._context_builder.build.return_value = ("context text", expected_sources)
        result = _run(orch.answer(QueryRequest(question="revenue", user_id=1)))
        assert result.sources == tuple(expected_sources)


# ---------------------------------------------------------------------------
# 9-10: HTTP /query and SSE done event shape
# ---------------------------------------------------------------------------

def _have_api_deps():
    try:
        import jose  # noqa: F401
        import bcrypt  # noqa: F401
        return True
    except ImportError:
        return False


class TestHTTPAndSSEBaseline:
    """Characterize the current /query and /query/stream response shapes.

    These tests use FastAPI TestClient with dependency overrides, mirroring
    the Phase 3 HTTP endpoint tests. They assert that the CURRENT shape has
    no ``validation`` / ``answerability`` / ``warnings`` keys — establishing
    the additive delta that Phase 4 will introduce.
    """

    @classmethod
    def _mock_engine_result(cls, *, answer="LLM answer", calculations=None):
        result = {
            "answer": answer,
            "sources": [{"doc_id": "chunk_001", "page": 12}],
            "searched_docs": ["annual_report.pdf"],
            "confidence": 0.9,
            "context_sufficient": True,
            "intent": "document_qa",
            "intent_confidence": 0.8,
            "trace_id": "trace_http_001",
            "rewritten_question": None,
            "retrieved_chunks": [],
            "retrieval_debug": {},
        }
        if calculations is not None:
            result["calculations"] = calculations
        return result

    def test_http_query_has_no_validation_field(self):
        pytest = __import__("pytest")
        if not _have_api_deps():
            pytest.skip("API deps (jose, bcrypt) not available")
        from fastapi.testclient import TestClient
        from src.main import app
        from src.services.auth import get_current_user

        mock_user = MagicMock()
        mock_user.id = 1
        mock_user.email = "test@test.com"
        app.dependency_overrides[get_current_user] = lambda: mock_user
        try:
            mock_engine = MagicMock()
            mock_engine.query = AsyncMock(return_value=self._mock_engine_result())
            with patch("src.main.get_rag_engine", return_value=mock_engine), \
                 patch("src.main._resolve_query_document_names_for_user", return_value=["annual_report.pdf"]), \
                 patch("src.main.memory_store"):
                client = TestClient(app)
                resp = client.post("/query", json={"question": "what is revenue", "document_names": ["annual_report.pdf"]})
                assert resp.status_code == 200
                body = resp.json()
                # Current shape: these Phase 4 keys must NOT exist yet.
                assert "validation" not in body
                assert "answerability" not in body
                assert "warnings" not in body
                # Existing fields remain.
                assert body["answer"] == "LLM answer"
                assert body["trace_id"] == "trace_http_001"
        finally:
            app.dependency_overrides.clear()

    def test_sse_done_event_has_no_validation_field(self):
        pytest = __import__("pytest")
        if not _have_api_deps():
            pytest.skip("API deps (jose, bcrypt) not available")
        from fastapi.testclient import TestClient
        from src.main import app
        from src.services.auth import get_current_user

        mock_user = MagicMock()
        mock_user.id = 1
        mock_user.email = "test@test.com"
        app.dependency_overrides[get_current_user] = lambda: mock_user
        try:
            mock_engine = MagicMock()
            mock_engine.query = AsyncMock(return_value=self._mock_engine_result(answer="stream answer"))
            with patch("src.main.get_rag_engine", return_value=mock_engine), \
                 patch("src.main._resolve_query_document_names_for_user", return_value=["annual_report.pdf"]), \
                 patch("src.main.memory_store"):
                client = TestClient(app)
                with client.stream("POST", "/query/stream",
                                   json={"question": "what is revenue", "document_names": ["annual_report.pdf"]}) as stream:
                    events = []
                    for line in stream.iter_lines():
                        if line.startswith("data: "):
                            events.append(json.loads(line[len("data: "):]))
                done = [e for e in events if e.get("type") == "done"]
                assert len(done) == 1
                payload = done[0]
                assert "validation" not in payload
                assert "answerability" not in payload
                assert "warnings" not in payload
                assert payload["trace_id"] == "trace_http_001"
        finally:
            app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 11: Trace diagnostics shape
# ---------------------------------------------------------------------------

class TestTraceBaseline:
    def test_trace_diagnostics_has_no_validation_key(self):
        orch = _make_orchestrator()
        _run(orch.answer(QueryRequest(question="revenue", user_id=1)))
        # Inspect the trace payload captured by the mocked logger.
        trace_payload = orch._trace_logger.log.call_args.kwargs
        diag = trace_payload.get("diagnostics", {})
        # Phase 3 trace diagnostics has confidence/context_sufficient/intent/
        # deterministic_answer/low_confidence_numeric_override/calculation.
        assert "validation" not in diag
        assert "answerability" not in diag
        assert "confidence" in diag
        assert "context_sufficient" in diag


# ---------------------------------------------------------------------------
# 12: Non-calculation answers have no validation field
# ---------------------------------------------------------------------------

class TestNoValidationFieldBaseline:
    def test_non_calculation_legacy_dict_has_no_validation(self):
        orch = _make_orchestrator()
        result = _run(orch.answer(QueryRequest(question="summarize the report", user_id=1)))
        legacy = result.to_legacy_dict()
        assert "validation" not in legacy
        assert "answerability" not in legacy
        # warnings only appears when non-empty (Phase 3 additive); ensure absent here.
        assert "warnings" not in legacy

    def test_calculation_legacy_dict_has_no_validation(self):
        orch = _make_orchestrator(
            calculation_pipeline=_StubPipeline(_executed_result())
        )
        result = _run(orch.answer(QueryRequest(question="gross margin?", user_id=1)))
        legacy = result.to_legacy_dict()
        assert "validation" not in legacy
        assert "answerability" not in legacy
        # calculations IS present for calculation results (Phase 3).
        assert "calculations" in legacy
