"""Tests for Phase 7 acceptance criteria (42 items).

Verify that ``artifacts/deployment/phase7/phase7-acceptance.json`` exists
(or can be generated by ``collect_deployment_report.py``), contains exactly
42 acceptance criteria, all criteria have a status field, and that the
expected criterion IDs are present.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS_DIR = REPO_ROOT / "artifacts" / "deployment" / "phase7"
ACCEPTANCE_PATH = ARTIFACTS_DIR / "phase7-acceptance.json"
COLLECT_SCRIPT = REPO_ROOT / "scripts" / "deploy" / "collect_deployment_report.py"

# 42 expected acceptance criterion IDs (matching Phase 7 spec exactly)
ACCEPTANCE_CRITERIA = [
    "created_from_phase6_master",
    "no_root_commands",
    "no_docker_dependency",
    "model_start_script",
    "backend_start_script",
    "frontend_start_script",
    "unified_start_script",
    "unified_stop_script",
    "unified_restart_script",
    "status_check_script",
    "start_order_correct",
    "stop_order_correct",
    "ports_above_1024",
    "bind_127.0.0.1",
    "backend_reload_disabled",
    "default_worker_one",
    "model_health_check",
    "backend_health_check",
    "frontend_health_check",
    "model_to_backend_link",
    "backend_to_frontend_link",
    "normal_qa_smoke",
    "calculation_smoke",
    "unanswerable_safe_fail",
    "sse_smoke",
    "log_separation",
    "no_secrets_in_logs",
    "no_cross_kill",
    "restart_recovery",
    "logout_persistence",
    "ssh_tunnel_access",
    "performance_report",
    "cpu_ram_gpu_recorded",
    "p50_p95_recorded",
    "artifact_sanitized",
    "deployment_docs",
    "full_tests_pass",
    "failed_zero",
    "errors_zero",
    "pr_created",
    "no_rag_algorithm_change",
    "no_phase_8",
]

assert len(ACCEPTANCE_CRITERIA) == 42


def _try_generate_artifact() -> bool:
    """Attempt to generate phase7-acceptance.json by running the collect script.

    Returns True if the artifact exists after the attempt.
    """
    if ACCEPTANCE_PATH.is_file():
        return True
    if not COLLECT_SCRIPT.is_file():
        return False
    try:
        subprocess.run(
            ["python", str(COLLECT_SCRIPT)],
            capture_output=True, text=True,
            cwd=str(REPO_ROOT), timeout=120,
        )
    except (subprocess.TimeoutExpired, OSError):
        pass
    return ACCEPTANCE_PATH.is_file()


def _load_json(path: Path) -> dict:
    if not path.exists():
        pytest.skip(f"Artifact not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _get_criteria_list(manifest: dict) -> list:
    """Extract the criteria list from the acceptance manifest."""
    for key in ["criteria", "acceptance_criteria", "items", "checks"]:
        if key in manifest:
            val = manifest[key]
            if isinstance(val, list):
                return val
            if isinstance(val, dict):
                return list(val.values())
    if isinstance(manifest, dict):
        vals = list(manifest.values())
        if all(isinstance(v, dict) for v in vals):
            return vals
    return []


def _criterion_ids(criteria: list) -> set[str]:
    """Return the set of all criterion IDs present in the criteria list."""
    ids: set[str] = set()
    for c in criteria:
        if not isinstance(c, dict):
            continue
        c_id = c.get("id") or c.get("name") or ""
        if c_id:
            ids.add(str(c_id))
    return ids


def _criterion_status(criteria: list, criterion_id: str) -> str | None:
    """Return the status of a specific criterion, or None if not found."""
    for c in criteria:
        if not isinstance(c, dict):
            continue
        c_id = str(c.get("id", "")) + str(c.get("name", ""))
        if criterion_id in c_id:
            return c.get("status") or c.get("result") or c.get("state")
    return None


@pytest.fixture
def acceptance_manifest() -> dict:
    """Load the acceptance artifact, attempting to generate it if missing."""
    if not ACCEPTANCE_PATH.is_file():
        _try_generate_artifact()
    return _load_json(ACCEPTANCE_PATH)


@pytest.fixture
def criteria_list(acceptance_manifest) -> list:
    """Extract the criteria list from the acceptance manifest."""
    criteria = _get_criteria_list(acceptance_manifest)
    if not criteria:
        pytest.skip("No criteria list found in phase7-acceptance.json")
    return criteria


def test_acceptance_artifact_exists_or_generated():
    # Test that phase7-acceptance.json exists (or can be generated)
    if not ACCEPTANCE_PATH.is_file():
        generated = _try_generate_artifact()
        assert generated, \
            f"phase7-acceptance.json does not exist and could not be generated from {COLLECT_SCRIPT}"


def test_acceptance_criteria_count(criteria_list):
    # Test that it contains exactly 42 acceptance criteria
    assert len(criteria_list) == 42, \
        f"Expected exactly 42 acceptance criteria, got {len(criteria_list)}"


def test_all_criteria_have_status(criteria_list):
    # Test that all criteria have a status field ("passed" or "pending")
    for i, c in enumerate(criteria_list):
        if not isinstance(c, dict):
            continue
        status = c.get("status")
        assert status is not None, \
            f"Criterion #{i} ({c.get('id', '?')}) has no status field"
        assert status in ("passed", "pending"), \
            f"Criterion '{c.get('id', '?')}' has unexpected status: {status}"


@pytest.mark.parametrize("criterion_id", ACCEPTANCE_CRITERIA)
def test_acceptance_criterion_exists(criteria_list, criterion_id):
    # Test that each expected criterion ID exists in the acceptance manifest
    ids = _criterion_ids(criteria_list)
    assert criterion_id in ids, \
        f"Criterion '{criterion_id}' not found in phase7-acceptance.json"


@pytest.mark.parametrize("criterion_id", ACCEPTANCE_CRITERIA)
def test_acceptance_criterion_status(criteria_list, criterion_id):
    # Test that each criterion has a valid status ("passed" or "pending")
    status = _criterion_status(criteria_list, criterion_id)
    assert status is not None, \
        f"Criterion '{criterion_id}' not found in acceptance criteria"
    status_lower = str(status).lower()
    assert status_lower in ("passed", "pending"), \
        f"Criterion '{criterion_id}' has unexpected status: {status}"
